---
- name: Restart vault
  ansible.builtin.command:
    cmd: docker compose restart
    chdir: /opt/vault
  tags: [vault]

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
  tags: [vault]
