---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sentinel-iac
  description: Infrastructure-as-Code for Project Sentinel (Ansible, Terraform, Packer)
  annotations:
    backstage.io/source-location: url:http://${GITLAB_IP}/${GITLAB_NAMESPACE}/sentinel-iac
  links:
    - url: http://${GITLAB_IP}/${GITLAB_NAMESPACE}/sentinel-iac/-/pipelines
      title: CI Pipeline
      icon: dashboard
  tags:
    - iac
    - ansible
    - terraform
spec:
  type: library
  lifecycle: production
  owner: platform-team
  system: sentinel-platform
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: compliance-pipeline-docs
  description: Compliance Pipeline TechDocs entity
spec:
  type: url
  target: ./techdocs/compliance-pipeline/catalog-info.yaml
