# =============================================================================
# Packer Template: minio-bootstrap (LXC 301) - Tier -1 Seed Infrastructure
# =============================================================================
# This LXC container runs MinIO object storage for Terraform state and
# rclone-based encrypted backups to Backblaze B2.
#
# IMPORTANT: Packer does NOT have a native Proxmox LXC builder. The
# hashicorp/proxmox plugin only supports proxmox-iso and proxmox-clone
# (both for QEMU VMs). This template uses a two-stage approach:
#
#   Stage 1 (Packer): Build an Ubuntu 24.04 VM with all MinIO components
#                      installed and configured, then convert to template.
#   Stage 2 (Manual): Use the Proxmox API/CLI to create the LXC from a
#                      standard Ubuntu 24.04 CT template, then run the
#                      setup script generated by this Packer build.
#
# For pure LXC disaster recovery, see the ALTERNATIVE section at the bottom
# which provides a standalone shell script that can be run directly on proxmox-node-3.
# =============================================================================

packer {
  required_plugins {
    proxmox = {
      version = ">= 1.1.2"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------

variable "proxmox_url" {
  type    = string
  default = "https://${PROXMOX_NODE1_IP}:8006/api2/json"
}

variable "proxmox_token_id" {
  description = "Proxmox API token ID"
  type        = string
  default     = "terraform-prov@pve!api-token"
}

variable "proxmox_token_secret" {
  description = "Proxmox API token secret (set via PKR_VAR_proxmox_token_secret)"
  type        = string
  sensitive   = true
}

variable "proxmox_node" {
  description = "Proxmox node to build on (proxmox-node-3 = R720xd)"
  type        = string
  default     = "proxmox-node-3"
}

variable "minio_root_user" {
  description = "MinIO root username"
  type        = string
  default     = "minio-admin"
}

variable "minio_root_password" {
  description = "MinIO root password (set via PKR_VAR_minio_root_password)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "b2_account_id" {
  description = "Backblaze B2 account ID (set via PKR_VAR_b2_account_id)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "b2_application_key" {
  description = "Backblaze B2 application key (set via PKR_VAR_b2_application_key)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "rclone_crypt_password" {
  description = "rclone crypt password (obscured, set via PKR_VAR_rclone_crypt_password)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "rclone_crypt_password2" {
  description = "rclone crypt salt (obscured, set via PKR_VAR_rclone_crypt_password2)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "ssh_password" {
  description = "Temporary SSH password for cloud-init build VM (set via PKR_VAR_ssh_password)"
  type        = string
  sensitive   = true
}

# -----------------------------------------------------------------------------
# Source: Ubuntu 24.04 VM (will be used as reference build; see notes above)
# -----------------------------------------------------------------------------
# Since Packer cannot directly build LXC containers, we build a reference VM
# that validates all provisioning steps. The real LXC is created via the
# shell script in the local-shell post-processor.

source "proxmox-clone" "minio-bootstrap" {
  proxmox_url              = var.proxmox_url
  username                 = var.proxmox_token_id
  token                    = var.proxmox_token_secret
  insecure_skip_tls_verify = true

  task_timeout = "5m"

  node    = var.proxmox_node
  vm_id   = 9301
  vm_name = "minio-bootstrap-ref"

  clone_vm   = "ubuntu-2404-ci"
  full_clone = true

  cores  = 2
  memory = 1024

  scsi_controller = "virtio-scsi-pci"

  disks {
    disk_size    = "8G"
    storage_pool = "local-lvm"
    type         = "scsi"
  }

  network_adapters {
    bridge = "vmbr0"
    model  = "virtio"
  }

  cloud_init              = true
  cloud_init_storage_pool = "local-lvm"

  ipconfig {
    ip      = "${VIP_5}/24"
    gateway = "${GATEWAY_IP}"
  }

  ssh_username = "ubuntu"
  ssh_password = var.ssh_password
  ssh_timeout  = "10m"
}

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

build {
  sources = ["source.proxmox-clone.minio-bootstrap"]

  # ---------------------------------------------------------------------------
  # Phase 1: Create minio-user and install MinIO
  # ---------------------------------------------------------------------------
  provisioner "shell" {
    inline = [
      "echo '>>> Phase 1: Installing MinIO'",
      "sudo apt-get update -y",
      "sudo apt-get install -y curl wget jq",

      # Create dedicated minio user
      "sudo groupadd -r minio-user || true",
      "sudo useradd -r -g minio-user -s /sbin/nologin minio-user || true",

      # Download MinIO server binary
      "wget -q https://dl.min.io/server/minio/release/linux-amd64/minio -O /tmp/minio",
      "sudo mv /tmp/minio /usr/local/bin/minio",
      "sudo chmod +x /usr/local/bin/minio",

      # Download MinIO client (mc)
      "wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /tmp/mc",
      "sudo mv /tmp/mc /usr/local/bin/mc",
      "sudo chmod +x /usr/local/bin/mc",

      # Create data directory
      "sudo mkdir -p /data/minio",
      "sudo chown -R minio-user:minio-user /data/minio",
    ]
  }

  # ---------------------------------------------------------------------------
  # Phase 2: Configure MinIO environment
  # ---------------------------------------------------------------------------
  provisioner "shell" {
    inline = [
      "echo '>>> Phase 2: Configuring MinIO environment'",

      # Write MinIO defaults file
      "sudo tee /etc/default/minio > /dev/null <<'MINIOCFG'",
      "# MinIO root credentials",
      "MINIO_ROOT_USER=${var.minio_root_user}",
      "MINIO_ROOT_PASSWORD=${var.minio_root_password != "" ? var.minio_root_password : "CHANGE_ME_AFTER_BUILD"}",
      "",
      "# Volume and address",
      "MINIO_VOLUMES=\"/data/minio\"",
      "MINIO_OPTS=\"--console-address :9001\"",
      "MINIOCFG",
      "sudo chmod 600 /etc/default/minio",
    ]
  }

  # ---------------------------------------------------------------------------
  # Phase 3: Create MinIO systemd service
  # ---------------------------------------------------------------------------
  provisioner "shell" {
    inline = [
      "echo '>>> Phase 3: Creating MinIO systemd service'",
      "sudo tee /etc/systemd/system/minio.service > /dev/null <<'SVCCFG'",
      "[Unit]",
      "Description=MinIO Object Storage",
      "Documentation=https://min.io/docs",
      "Wants=network-online.target",
      "After=network-online.target",
      "",
      "[Service]",
      "User=minio-user",
      "Group=minio-user",
      "EnvironmentFile=/etc/default/minio",
      "ExecStart=/usr/local/bin/minio server $MINIO_OPTS $MINIO_VOLUMES",
      "Restart=always",
      "RestartSec=5",
      "LimitNOFILE=65536",
      "TasksMax=infinity",
      "TimeoutStopSec=infinity",
      "SendSIGKILL=no",
      "",
      "[Install]",
      "WantedBy=multi-user.target",
      "SVCCFG",
      "sudo systemctl daemon-reload",
      "sudo systemctl enable minio",
    ]
  }

  # ---------------------------------------------------------------------------
  # Phase 4: Install and configure rclone for B2 backups
  # ---------------------------------------------------------------------------
  provisioner "shell" {
    inline = [
      "echo '>>> Phase 4: Installing rclone'",
      "curl -fsSL https://rclone.org/install.sh | sudo bash",

      # Create rclone config directory
      "sudo mkdir -p /root/.config/rclone",

      # Write rclone configuration
      "sudo tee /root/.config/rclone/rclone.conf > /dev/null <<RCLCFG",
      "[b2]",
      "type = b2",
      "account = ${var.b2_account_id != "" ? var.b2_account_id : "CHANGE_ME"}",
      "key = ${var.b2_application_key != "" ? var.b2_application_key : "CHANGE_ME"}",
      "",
      "[minio]",
      "type = s3",
      "provider = Minio",
      "access_key_id = ${var.minio_root_user}",
      "secret_access_key = ${var.minio_root_password != "" ? var.minio_root_password : "CHANGE_ME"}",
      "endpoint = http://127.0.0.1:9000",
      "",
      "[b2-encrypted]",
      "type = crypt",
      "remote = b2:haist-terraform-backup/encrypted/",
      "password = ${var.rclone_crypt_password != "" ? var.rclone_crypt_password : "CHANGE_ME"}",
      "password2 = ${var.rclone_crypt_password2 != "" ? var.rclone_crypt_password2 : "CHANGE_ME"}",
      "filename_encryption = standard",
      "directory_name_encryption = true",
      "RCLCFG",
      "sudo chmod 600 /root/.config/rclone/rclone.conf",
    ]
  }

  # ---------------------------------------------------------------------------
  # Phase 5: Create B2 backup script and timer
  # ---------------------------------------------------------------------------
  provisioner "shell" {
    inline = [
      "echo '>>> Phase 5: Creating B2 backup service'",

      # Backup script
      "sudo tee /usr/local/bin/backup-to-b2.sh > /dev/null <<'BKSCRIPT'",
      "#!/bin/bash",
      "# Sync MinIO terraform state to Backblaze B2 (ENCRYPTED)",
      "/usr/local/bin/rclone sync minio:terraform-state/ b2-encrypted:terraform-state/ --log-file=/var/log/b2-backup.log --log-level INFO",
      "BKSCRIPT",
      "sudo chmod +x /usr/local/bin/backup-to-b2.sh",

      # Systemd service for backup
      "sudo tee /etc/systemd/system/b2-backup.service > /dev/null <<'BKSVC'",
      "[Unit]",
      "Description=Backup MinIO to Backblaze B2",
      "",
      "[Service]",
      "Type=oneshot",
      "ExecStart=/usr/local/bin/backup-to-b2.sh",
      "User=root",
      "BKSVC",

      # Systemd timer (hourly)
      "sudo tee /etc/systemd/system/b2-backup.timer > /dev/null <<'BKTIMER'",
      "[Unit]",
      "Description=Hourly backup to Backblaze B2",
      "",
      "[Timer]",
      "OnBootSec=5min",
      "OnUnitActiveSec=1h",
      "Persistent=true",
      "",
      "[Install]",
      "WantedBy=timers.target",
      "BKTIMER",

      "sudo systemctl daemon-reload",
      "sudo systemctl enable b2-backup.timer",
    ]
  }

  # ---------------------------------------------------------------------------
  # Phase 6: Cleanup
  # ---------------------------------------------------------------------------
  provisioner "shell" {
    inline = [
      "echo '>>> Phase 6: Cleanup'",
      "sudo apt-get clean",
      "sudo rm -rf /var/lib/apt/lists/*",
      "sudo cloud-init clean --logs || true",
      "sync",
    ]
  }

  # ---------------------------------------------------------------------------
  # Post-processor: Generate standalone LXC setup script for DR
  # ---------------------------------------------------------------------------
  post-processor "shell-local" {
    inline = [
      "cat > minio-bootstrap-lxc-setup.sh <<'LXCSCRIPT'",
      "#!/bin/bash",
      "# ==========================================================================",
      "# MinIO Bootstrap LXC Setup Script - Disaster Recovery",
      "# ==========================================================================",
      "# Run this script on the Proxmox host (proxmox-node-3 / ${PROXMOX_NODE3_IP}) to recreate",
      "# the minio-bootstrap LXC container from scratch.",
      "#",
      "# Prerequisites:",
      "#   - Ubuntu 24.04 CT template downloaded:",
      "#     pveam download local ubuntu-24.04-standard_24.04-2_amd64.tar.zst",
      "#",
      "# Usage:",
      "#   bash minio-bootstrap-lxc-setup.sh",
      "#",
      "# After running, you MUST manually configure secrets in:",
      "#   /etc/default/minio",
      "#   /root/.config/rclone/rclone.conf",
      "# ==========================================================================",
      "set -euo pipefail",
      "",
      "CTID=301",
      "CT_NAME='minio-bootstrap'",
      "CT_TEMPLATE='local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst'",
      "CT_STORAGE='local-lvm'",
      "CT_DISK='8'",
      "CT_MEM='1024'",
      "CT_SWAP='512'",
      "CT_CORES='2'",
      "CT_IP='${MINIO_PRIMARY_IP}/24'",
      "CT_GW='${GATEWAY_IP}'",
      "CT_NS='${GATEWAY_IP}'",
      "CT_DOMAIN='${DOMAIN}'",
      "",
      "echo '>>> Creating LXC container...'",
      "pct create $CTID $CT_TEMPLATE \\",
      "  --hostname $CT_NAME \\",
      "  --storage $CT_STORAGE \\",
      "  --rootfs ${CT_STORAGE}:${CT_DISK} \\",
      "  --memory $CT_MEM \\",
      "  --swap $CT_SWAP \\",
      "  --cores $CT_CORES \\",
      "  --net0 name=eth0,bridge=vmbr0,gw=${CT_GW},ip=${CT_IP},type=veth \\",
      "  --nameserver $CT_NS \\",
      "  --searchdomain $CT_DOMAIN \\",
      "  --features nesting=1 \\",
      "  --unprivileged 1 \\",
      "  --onboot 1 \\",
      "  --start 1",
      "",
      "echo '>>> Waiting for container to start...'",
      "sleep 5",
      "",
      "echo '>>> Installing packages...'",
      "pct exec $CTID -- apt-get update -y",
      "pct exec $CTID -- apt-get install -y curl wget jq",
      "",
      "echo '>>> Creating minio-user...'",
      "pct exec $CTID -- groupadd -r minio-user",
      "pct exec $CTID -- useradd -r -g minio-user -s /sbin/nologin minio-user",
      "",
      "echo '>>> Downloading MinIO...'",
      "pct exec $CTID -- bash -c 'wget -q https://dl.min.io/server/minio/release/linux-amd64/minio -O /usr/local/bin/minio && chmod +x /usr/local/bin/minio'",
      "pct exec $CTID -- bash -c 'wget -q https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc && chmod +x /usr/local/bin/mc'",
      "",
      "echo '>>> Creating data directory...'",
      "pct exec $CTID -- mkdir -p /data/minio",
      "pct exec $CTID -- chown -R minio-user:minio-user /data/minio",
      "",
      "echo '>>> Configuring MinIO...'",
      "pct exec $CTID -- bash -c 'cat > /etc/default/minio <<EOF",
      "# MinIO root credentials - UPDATE THESE",
      "MINIO_ROOT_USER=minio-admin",
      "MINIO_ROOT_PASSWORD=CHANGE_ME_AFTER_BUILD",
      "",
      "# Volume and address",
      "MINIO_VOLUMES=\"/data/minio\"",
      "MINIO_OPTS=\"--console-address :9001\"",
      "EOF'",
      "pct exec $CTID -- chmod 600 /etc/default/minio",
      "",
      "echo '>>> Creating MinIO systemd service...'",
      "pct exec $CTID -- bash -c 'cat > /etc/systemd/system/minio.service <<EOF",
      "[Unit]",
      "Description=MinIO Object Storage",
      "Documentation=https://min.io/docs",
      "Wants=network-online.target",
      "After=network-online.target",
      "",
      "[Service]",
      "User=minio-user",
      "Group=minio-user",
      "EnvironmentFile=/etc/default/minio",
      "ExecStart=/usr/local/bin/minio server \\$MINIO_OPTS \\$MINIO_VOLUMES",
      "Restart=always",
      "RestartSec=5",
      "LimitNOFILE=65536",
      "TasksMax=infinity",
      "TimeoutStopSec=infinity",
      "SendSIGKILL=no",
      "",
      "[Install]",
      "WantedBy=multi-user.target",
      "EOF'",
      "",
      "echo '>>> Installing rclone...'",
      "pct exec $CTID -- bash -c 'curl -fsSL https://rclone.org/install.sh | bash'",
      "",
      "echo '>>> Configuring rclone...'",
      "pct exec $CTID -- mkdir -p /root/.config/rclone",
      "pct exec $CTID -- bash -c 'cat > /root/.config/rclone/rclone.conf <<EOF",
      "[b2]",
      "type = b2",
      "account = CHANGE_ME_B2_ACCOUNT_ID",
      "key = CHANGE_ME_B2_APP_KEY",
      "",
      "[minio]",
      "type = s3",
      "provider = Minio",
      "access_key_id = minio-admin",
      "secret_access_key = CHANGE_ME_MINIO_PASSWORD",
      "endpoint = http://127.0.0.1:9000",
      "",
      "[b2-encrypted]",
      "type = crypt",
      "remote = b2:haist-terraform-backup/encrypted/",
      "password = CHANGE_ME_RCLONE_CRYPT_PASS",
      "password2 = CHANGE_ME_RCLONE_CRYPT_SALT",
      "filename_encryption = standard",
      "directory_name_encryption = true",
      "EOF'",
      "pct exec $CTID -- chmod 600 /root/.config/rclone/rclone.conf",
      "",
      "echo '>>> Creating backup script...'",
      "pct exec $CTID -- bash -c 'cat > /usr/local/bin/backup-to-b2.sh <<EOF",
      "#!/bin/bash",
      "# Sync MinIO terraform state to Backblaze B2 (ENCRYPTED)",
      "/usr/local/bin/rclone sync minio:terraform-state/ b2-encrypted:terraform-state/ --log-file=/var/log/b2-backup.log --log-level INFO",
      "EOF'",
      "pct exec $CTID -- chmod +x /usr/local/bin/backup-to-b2.sh",
      "",
      "echo '>>> Creating backup timer...'",
      "pct exec $CTID -- bash -c 'cat > /etc/systemd/system/b2-backup.service <<EOF",
      "[Unit]",
      "Description=Backup MinIO to Backblaze B2",
      "",
      "[Service]",
      "Type=oneshot",
      "ExecStart=/usr/local/bin/backup-to-b2.sh",
      "User=root",
      "EOF'",
      "",
      "pct exec $CTID -- bash -c 'cat > /etc/systemd/system/b2-backup.timer <<EOF",
      "[Unit]",
      "Description=Hourly backup to Backblaze B2",
      "",
      "[Timer]",
      "OnBootSec=5min",
      "OnUnitActiveSec=1h",
      "Persistent=true",
      "",
      "[Install]",
      "WantedBy=timers.target",
      "EOF'",
      "",
      "echo '>>> Enabling services...'",
      "pct exec $CTID -- systemctl daemon-reload",
      "pct exec $CTID -- systemctl enable minio",
      "pct exec $CTID -- systemctl start minio",
      "pct exec $CTID -- systemctl enable b2-backup.timer",
      "pct exec $CTID -- systemctl start b2-backup.timer",
      "",
      "echo '>>> Creating terraform-state bucket...'",
      "sleep 3",
      "pct exec $CTID -- bash -c '/usr/local/bin/mc alias set local http://127.0.0.1:9000 minio-admin CHANGE_ME_MINIO_PASSWORD'",
      "pct exec $CTID -- bash -c '/usr/local/bin/mc mb local/terraform-state --ignore-existing'",
      "",
      "echo ''",
      "echo '========================================='",
      "echo '  MinIO Bootstrap LXC Created!'",
      "echo '========================================='",
      "echo ''",
      "echo 'IMPORTANT: Update secrets in these files:'",
      "echo '  pct exec $CTID -- vi /etc/default/minio'",
      "echo '  pct exec $CTID -- vi /root/.config/rclone/rclone.conf'",
      "echo ''",
      "echo 'Then restart MinIO:'",
      "echo '  pct exec $CTID -- systemctl restart minio'",
      "echo ''",
      "echo 'To restore from B2 backup:'",
      "echo '  pct exec $CTID -- rclone sync b2-encrypted:terraform-state/ minio:terraform-state/'",
      "echo ''",
      "LXCSCRIPT",
      "chmod +x minio-bootstrap-lxc-setup.sh",
      "echo '>>> Generated minio-bootstrap-lxc-setup.sh for LXC disaster recovery'",
    ]
  }

  post-processor "manifest" {
    output     = "minio-bootstrap-manifest.json"
    strip_path = true
  }
}
