[control_node]
iac-control ansible_connection=local

[git_servers]
gitlab-server ansible_host=${GITLAB_IP} ansible_user=${USERNAME}

[iac_control]
iac-control ansible_host=localhost ansible_connection=local

[config_servers]
config-server ansible_host=${OKD_GATEWAY} ansible_user=${USERNAME}
