---
- name: restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true

- name: restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: true

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true

- name: restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
