name: Sentinel Cluster Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'manifests/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to K3s Cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${OKD_NODE_IP}
          username: root
          key: ${{ secrets.SENTINEL_SSH_KEY }}
          script: |
            cd /home/${USERNAME}/project-sentinel-k3s
            git pull origin master
            kubectl apply -f manifests/
